version: '3.8'

services:
  vnc-server:
    image: jkoubi/koubot_vnc:v4
    container_name: my_koubot_vnc_v4_container
    network_mode: host # network
    privileged: true
    cap_add:
      - SYS_RAWIO
    # ports:
    #   - "5901:5901"
    environment:
      DISPLAY: ":1"
      GEOMETRY: "1920x1080"
      DEPTH: "24"
      ROS_DOMAIN_ID: "10"
      ROS_LOCALHOST_ONLY: "0"
    volumes:
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./vnc_passwd/passwd:/root/.vnc/passwd:ro  # Ensure the password file is mounted correctly
      - /home/ubuntu/KouBot-ROS2/ros2_ws/src:/ros2_ws/src:rw
      - /dev:/dev
    device_cgroup_rules:
      - 'c 188:* rmw'
    command: >
      /bin/bash -c "
      mkdir -p /root/.vnc &&
      vncserver :1 -geometry 1920x1080 -depth 24 -localhost no &&
      tail -f /dev/null"