amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_footprint
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: /scan
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.2
    update_min_a: 0.1
    resample_interval: 1
    transform_tolerance: 1.0
    laser_model_type: likelihood_field
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    tf_broadcast: true
    queue_size: 100
    transform_tolerance: 4.0
