slam_toolbox:
  ros__parameters:
    use_sim_time: false
    resolution: 0.05
    publish_map_to_odom: true
    map_update_interval: 2.0
    scan_topic: scan
    mode: mapping
    use_pose_graph: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.05
    loop_closure_enabled: true
    tf_buffer_duration: 10.0
    transform_timeout: 1.0
    max_laser_range: 8.0
    range_data_trim_min: 0.05
    range_data_trim_max: 8.0
    minimum_time_interval: 0.1
    queue_size: 50